import { StyleSheet } from "react-native";
import { STATUS_BAR_HEIGHT } from "../../constants";

export const styles = StyleSheet.create({
  header: {
    paddingHorizontal: 24,
    paddingTop: STATUS_BAR_HEIGHT + 24,
    paddingBottom: 24,
  },
  greetRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  greeting: { color: "#f8fafc", fontSize: 30, fontWeight: "800" },
  sparkle: { fontSize: 24, color: "#facc15" },
  subGreeting: { color: "#cbd5e1", fontSize: 15, marginTop: 4 },
  statsCard: {
    marginTop: 22,
    backgroundColor: "rgba(30, 41, 59, 0.7)",
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.15)",
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  statsLabel: { color: "#94a3b8", fontSize: 13, marginBottom: 4 },
  statsValue: { color: "#f8fafc", fontSize: 22, fontWeight: "700" },
  percentBadge: {
    backgroundColor: "#7c3aed",
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 999,
    shadowColor: "#a78bfa",
    shadowOpacity: 0.7,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
  percentText: { color: "#fff", fontWeight: "800", fontSize: 14 },
  progressTrack: {
    height: 10,
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    borderRadius: 999,
    overflow: "hidden",
  },
  progressFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "#a78bfa",
    borderRadius: 999,
  },
  progressGlow: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "#ec4899",
    borderRadius: 999,
    opacity: 0.5,
  },
  shimmer: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 60,
    backgroundColor: "rgba(255, 255, 255, 0.55)",
    borderRadius: 999,
    transform: [{ skewX: "-20deg" }],
  },
});
