import { Platform, StyleSheet } from "react-native";

export const colors = {
  primary: "#16A34A",
  primaryDark: "#15803D",
  primarySoft: "#DCFCE7",
  accent: "#7C3AED",
  accentSoft: "#EDE9FE",
  screenTime: "#3B82F6",
  screenTimeSoft: "#DBEAFE",
  points: "#F59E0B",
  pointsSoft: "#FEF3C7",
  cash: "#10B981",
  cashSoft: "#D1FAE5",
  trophy: "#F59E0B",
  warning: "#F59E0B",
  warningSoft: "#FEF3C7",
  danger: "#EF4444",
  dangerSoft: "#FEE2E2",
  background: "#F8FAFC",
  surface: "#FFFFFF",
  surfaceAlt: "#F1F5F9",
  border: "#E2E8F0",
  borderStrong: "#CBD5E1",
  text: "#0F172A",
  textSoft: "#334155",
  muted: "#64748B",
  locked: "#94A3B8",
  navInactive: "#94A3B8",
};

const elevated = Platform.select({
  ios: {
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
  },
  android: { elevation: 2 },
  default: {},
});

const lift = Platform.select({
  ios: {
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
  },
  android: { elevation: 5 },
  default: {},
});

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    paddingTop: 48,
    paddingHorizontal: 18,
    paddingBottom: 110,
  },

  // Top bar (in-task)
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 56,
    paddingBottom: 12,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  topBarBack: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  topBarBackText: {
    fontSize: 18,
    color: colors.text,
    fontWeight: "700",
  },
  topBarTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.text,
    flex: 1,
    textAlign: "center",
  },
  topBarRight: {
    width: 36,
  },

  // Brand row (home)
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  brandLogo: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    ...elevated,
  },
  brandLogoText: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "800",
  },
  brandTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.text,
  },
  brandSub: {
    fontSize: 13,
    color: colors.muted,
  },

  // Status hero
  hero: {
    borderRadius: 24,
    padding: 24,
    marginBottom: 22,
    minHeight: 180,
    overflow: "hidden",
    ...lift,
  },
  heroLocked: {
    backgroundColor: "#0F172A",
  },
  heroUnlocked: {
    backgroundColor: colors.primary,
  },
  heroGlow: {
    position: "absolute",
    width: 220,
    height: 220,
    borderRadius: 110,
    opacity: 0.25,
  },
  heroLabel: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 11,
    letterSpacing: 1.5,
    fontWeight: "700",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  heroTitle: {
    color: "#fff",
    fontSize: 26,
    fontWeight: "800",
    marginBottom: 4,
  },
  heroSub: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 14,
  },
  heroCountdown: {
    color: "#fff",
    fontSize: 44,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
    marginTop: 12,
  },

  // Section
  sectionLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.muted,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 10,
    marginTop: 10,
  },
  sectionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    marginTop: 10,
  },

  // App tiles grid (mobile home-screen style)
  appsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -6,
    marginBottom: 6,
  },
  appTile: {
    width: "25%",
    paddingHorizontal: 6,
    alignItems: "center",
    marginBottom: 14,
  },
  appTileIconWrap: {
    width: 60,
    height: 60,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  appTileIconLocked: {},
  appTileLockedOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 16,
    backgroundColor: "rgba(15, 23, 42, 0.32)",
  },
  appTileLockBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#0F172A",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.background,
  },
  appTileUnlockBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.background,
  },
  appTileLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.textSoft,
    marginTop: 6,
    textAlign: "center",
  },
  appTileLabelLocked: {
    color: colors.muted,
  },

  // Task card (home list)
  taskCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
    ...elevated,
  },
  taskHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  taskTypeBadge: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  taskTypeBadgeText: {
    fontSize: 22,
  },
  taskTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: colors.text,
    marginBottom: 2,
  },
  taskDesc: {
    fontSize: 13,
    color: colors.muted,
  },
  taskFab: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 5,
  },
  taskFabPressed: {
    backgroundColor: colors.primaryDark,
    transform: [{ scale: 0.94 }],
  },
  taskDividerThin: {
    height: 1,
    backgroundColor: colors.border,
    marginTop: 12,
    marginBottom: 10,
  },

  // Mini reward pills
  miniRewardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  miniRewardPill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  miniRewardPillText: {
    fontSize: 12,
    fontWeight: "800",
    marginLeft: 4,
  },

  // Reward chips row (3 rewards on each task)
  rewardsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 6,
    marginBottom: 12,
    gap: 8,
  },
  rewardCol: {
    flex: 1,
    alignItems: "center",
    backgroundColor: colors.surfaceAlt,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 6,
  },
  rewardColValue: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.text,
  },
  rewardColLabel: {
    fontSize: 9,
    fontWeight: "700",
    color: colors.muted,
    letterSpacing: 1,
    textTransform: "uppercase",
    marginTop: 2,
  },
  rewardColScreen: {
    color: colors.screenTime,
  },
  rewardColPoints: {
    color: colors.points,
  },
  rewardColCash: {
    color: colors.cash,
  },

  // Reward picker (choose your reward) - selectable
  rewardPickerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 6,
    marginBottom: 14,
  },
  rewardPick: {
    flex: 1,
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 14,
    paddingVertical: 14,
    borderWidth: 2,
    borderColor: colors.border,
  },
  rewardPickSelected: {
    transform: [{ scale: 1.02 }],
  },
  rewardPickIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  rewardPickIconText: {
    fontSize: 22,
  },

  rewardChooseLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.muted,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginTop: 2,
    marginBottom: 6,
  },

  // Buttons
  primaryButton: {
    flexDirection: "row",
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    ...elevated,
  },
  primaryButtonPressed: {
    backgroundColor: colors.primaryDark,
    transform: [{ scale: 0.98 }],
  },
  primaryButtonDisabled: {
    backgroundColor: colors.locked,
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 15,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  accentButton: {
    flexDirection: "row",
    backgroundColor: colors.accent,
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    ...elevated,
  },
  ghostButton: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  ghostButtonText: {
    color: colors.text,
    fontWeight: "700",
    fontSize: 14,
  },

  // Task detail screen
  screenContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  taskBody: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 100,
  },
  illustrationBox: {
    backgroundColor: "#E0F2FE",
    borderRadius: 20,
    aspectRatio: 16 / 10,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
    overflow: "hidden",
  },
  illustrationEmoji: {
    fontSize: 80,
  },
  taskHeadline: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.text,
    textAlign: "center",
    marginBottom: 16,
  },

  // Walk task
  walkTimer: {
    fontSize: 56,
    fontWeight: "800",
    color: colors.text,
    fontVariant: ["tabular-nums"],
    textAlign: "center",
  },
  walkTimerSub: {
    fontSize: 16,
    color: colors.muted,
    textAlign: "center",
    marginTop: -4,
  },
  walkStatsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: 14,
  },
  walkStatCol: {
    alignItems: "center",
  },
  walkStatLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.muted,
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  walkStatValue: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.text,
  },
  walkStatusPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  walkStatusPillText: {
    color: colors.primaryDark,
    fontSize: 12,
    fontWeight: "700",
  },
  progressTrack: {
    height: 8,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 999,
    overflow: "hidden",
    marginTop: 6,
  },
  progressFill: {
    height: "100%",
    backgroundColor: colors.primary,
    borderRadius: 999,
  },
  progressLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 6,
  },
  progressLabel: {
    fontSize: 11,
    color: colors.muted,
    fontWeight: "600",
  },

  // Quiz
  quizQuestionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  quizQuestionCounter: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.text,
  },
  quizPerQuestionTimer: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.muted,
    fontVariant: ["tabular-nums"],
  },
  quizQuestionText: {
    fontSize: 19,
    fontWeight: "800",
    color: colors.text,
    lineHeight: 26,
    marginBottom: 18,
  },
  optionRow: {
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  optionRowSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  optionRowCorrect: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  optionRowWrong: {
    borderColor: colors.danger,
    backgroundColor: colors.dangerSoft,
  },
  optionLetter: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  optionLetterSelected: {
    backgroundColor: colors.primary,
  },
  optionLetterText: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.muted,
  },
  optionLetterTextSelected: {
    color: "#fff",
  },
  optionText: {
    flex: 1,
    fontSize: 15,
    color: colors.text,
    fontWeight: "500",
  },
  quizDots: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    marginTop: 16,
    marginBottom: 6,
  },
  quizDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  quizDotActive: {
    backgroundColor: colors.primary,
  },
  quizDotDone: {
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  quizDotText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.muted,
  },
  quizDotTextActive: {
    color: "#fff",
  },
  quizDotTextDone: {
    color: colors.primaryDark,
  },

  // Photo
  cameraFrame: {
    backgroundColor: "#0F172A",
    borderRadius: 20,
    aspectRatio: 9 / 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
    overflow: "hidden",
    position: "relative",
  },
  cameraImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "#475569",
    alignItems: "center",
    justifyContent: "center",
  },
  cameraImageEmoji: {
    fontSize: 72,
  },
  cameraTopBar: {
    position: "absolute",
    top: 14,
    left: 14,
    right: 14,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cameraIconBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  cameraIconText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  cameraBottomBar: {
    position: "absolute",
    bottom: 18,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  cameraSwitchRow: {
    flexDirection: "row",
    backgroundColor: "rgba(0,0,0,0.4)",
    borderRadius: 999,
    padding: 4,
    marginBottom: 12,
  },
  cameraSwitchPill: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
  },
  cameraSwitchPillActive: {
    backgroundColor: "rgba(255,255,255,0.95)",
  },
  cameraSwitchText: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
  },
  cameraSwitchTextActive: {
    color: "#0F172A",
  },
  shutterOuter: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 4,
    borderColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  shutterInner: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#fff",
  },
  photoActionRow: {
    flexDirection: "row",
    gap: 10,
  },
  photoActionGhost: {
    flex: 1,
  },
  photoActionPrimary: {
    flex: 2,
  },

  // Pending / approved
  hourglassWrap: {
    backgroundColor: colors.accentSoft,
    borderRadius: 20,
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 20,
    marginHorizontal: 40,
  },
  hourglassEmoji: {
    fontSize: 88,
  },
  pendingTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.text,
    textAlign: "center",
    marginBottom: 6,
  },
  pendingText: {
    fontSize: 14,
    color: colors.muted,
    textAlign: "center",
    paddingHorizontal: 20,
  },

  // Mission complete
  missionContainer: {
    flex: 1,
    backgroundColor: "#0F172A",
    paddingTop: 56,
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  missionCard: {
    backgroundColor: "#1E293B",
    borderRadius: 24,
    padding: 28,
    alignItems: "center",
    marginTop: 18,
    ...lift,
  },
  missionTitle: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 16,
  },
  trophyWrap: {
    width: 140,
    height: 140,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  trophyEmoji: {
    fontSize: 96,
  },
  earnedLabel: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 14,
  },
  earnedRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    gap: 10,
    marginBottom: 18,
  },
  earnedCol: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  earnedColValue: {
    fontSize: 18,
    fontWeight: "800",
    color: "#fff",
  },
  earnedColLabel: {
    fontSize: 9,
    fontWeight: "700",
    color: "rgba(255,255,255,0.6)",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginTop: 2,
  },
  rewardChosenLabel: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  rewardChosenChip: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 14,
    width: 60,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },

  // Bottom nav
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 8,
    paddingBottom: 24,
    paddingHorizontal: 12,
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 4,
  },
  navIcon: {
    fontSize: 20,
    marginBottom: 2,
  },
  navLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.navInactive,
  },
  navLabelActive: {
    color: colors.primary,
  },

  footerNote: {
    fontSize: 11,
    color: colors.muted,
    textAlign: "center",
    marginTop: 14,
  },

  // Generic page header (Progress / Rewards / Menu)
  pageHeader: {
    fontSize: 28,
    fontWeight: "800",
    color: colors.text,
    marginBottom: 4,
  },
  pageSub: {
    fontSize: 14,
    color: colors.muted,
    marginBottom: 22,
  },

  // Tab hero
  tabHero: {
    borderRadius: 24,
    padding: 20,
    marginBottom: 22,
    overflow: "hidden",
    minHeight: 150,
    ...lift,
  },
  tabHeroLabel: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  tabHeroValue: {
    color: "#fff",
    fontSize: 44,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
  },
  tabHeroSub: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 14,
    marginTop: 4,
  },

  // Mini bar chart
  chartRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    height: 100,
    gap: 8,
    marginTop: 12,
    marginBottom: 6,
  },
  chartBarWrap: {
    flex: 1,
    height: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  chartBar: {
    width: "70%",
    backgroundColor: colors.primary,
    borderRadius: 6,
    minHeight: 4,
  },
  chartBarTrack: {
    width: "70%",
    height: "100%",
    backgroundColor: colors.surfaceAlt,
    borderRadius: 6,
    position: "absolute",
    bottom: 0,
  },
  chartLabels: {
    flexDirection: "row",
    gap: 8,
  },
  chartLabel: {
    flex: 1,
    fontSize: 10,
    fontWeight: "700",
    color: colors.muted,
    textAlign: "center",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },

  // Home greeting
  greetingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  greetingAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    position: "relative",
  },
  greetingAvatarText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "800",
  },
  greetingDot: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.danger,
    borderWidth: 2,
    borderColor: colors.background,
  },
  greetingHi: {
    fontSize: 12,
    color: colors.muted,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  greetingName: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.text,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },

  // Status bar (compact mobile)
  statusBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0F172A",
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 18,
    overflow: "hidden",
    ...elevated,
  },
  statusBarIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "rgba(251,191,36,0.3)",
  },
  statusBarLabel: {
    color: "#FBBF24",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  statusBarText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
    marginTop: 2,
  },
  statusBarChevron: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  statusBarExpanded: {
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
  },
  statusDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
  },
  statusDetailIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.06)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  statusDetailLabel: {
    color: "rgba(255,255,255,0.65)",
    fontSize: 13,
    flex: 1,
  },
  statusDetailValue: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
  },
  statusTip: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 12,
    fontStyle: "italic",
    marginTop: 8,
    textAlign: "center",
  },

  // Horizontal stat cards scroll
  hScroll: {
    marginHorizontal: -18,
    marginBottom: 18,
  },
  hScrollContent: {
    paddingHorizontal: 18,
    gap: 8,
  },
  miniStatCard: {
    width: 108,
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
    ...elevated,
  },
  miniStatIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  miniStatValue: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.text,
  },
  miniStatLabel: {
    fontSize: 10,
    color: colors.muted,
    fontWeight: "700",
    marginTop: 2,
    letterSpacing: 0.4,
  },

  // Featured locked hero (Home)
  homeHero: {
    backgroundColor: "#0F172A",
    borderRadius: 28,
    padding: 24,
    marginBottom: 22,
    overflow: "hidden",
    minHeight: 230,
    ...lift,
  },
  homeHeroLockBox: {
    width: 76,
    height: 76,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  homeHeroStatus: {
    color: "#FBBF24",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  homeHeroBigText: {
    color: "#fff",
    fontSize: 30,
    fontWeight: "800",
    marginBottom: 4,
  },
  homeHeroDesc: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 14,
    lineHeight: 20,
  },
  homeHeroDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.1)",
    marginVertical: 16,
  },
  homeHeroFooter: {
    flexDirection: "row",
    alignItems: "center",
  },
  homeHeroFooterCol: {
    flex: 1,
  },
  homeHeroFooterLabel: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  homeHeroFooterValue: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "800",
    marginTop: 2,
  },

  // Pairing code card
  pairingCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 18,
    ...elevated,
  },
  pairingLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.muted,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  pairingCode: {
    fontSize: 26,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: 4,
    fontVariant: ["tabular-nums"],
    marginTop: 4,
  },

  // Stat grid (Progress)
  statGrid: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 22,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statValue: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.text,
    marginTop: 8,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.muted,
    letterSpacing: 1,
    textTransform: "uppercase",
    marginTop: 2,
  },

  // History row
  historyRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  historyIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  historyTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.text,
  },
  historyMeta: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 2,
  },
  historyReward: {
    fontSize: 14,
    fontWeight: "800",
  },

  // Bank card (Rewards)
  bankCard: {
    borderRadius: 18,
    padding: 18,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  bankIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
    backgroundColor: "rgba(255,255,255,0.25)",
  },
  bankLabel: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  bankValue: {
    color: "#fff",
    fontSize: 26,
    fontWeight: "800",
    marginTop: 2,
  },

  // Menu list
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  menuRowIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    backgroundColor: colors.surfaceAlt,
  },
  menuRowLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: "600",
    color: colors.text,
  },
  menuRowValue: {
    fontSize: 13,
    color: colors.muted,
    marginRight: 6,
    fontWeight: "600",
  },

  profileBlock: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 18,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: colors.border,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  avatarText: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "800",
  },
  profileName: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.text,
  },
  profileMeta: {
    fontSize: 13,
    color: colors.muted,
    marginTop: 2,
  },

  emptyBox: {
    alignItems: "center",
    paddingVertical: 32,
  },
  emptyText: {
    fontSize: 14,
    color: colors.muted,
    marginTop: 10,
  },
});
